import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { Providers } from '@/components/providers';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth/next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { SessionProvider } from '@/components/session-provider';

import './globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async  function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	const session = await getServerSession(authOptions);
	return (
		<html lang="en">
			<body className={inter.className}>
				<SessionProvider session={session}>
					<Providers>
						{children}
					</Providers>
				</SessionProvider>
			</body>
		</html>
	);
}
