import { auth } from '@/auth';
import { Providers } from '@/components/providers';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { SessionProvider } from '@/components/session-provider';

import './globals.css';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async  function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	const session = await auth()
	return (
		<html lang="en" className={'h-full'}>
			<body className={cn(inter.className, 'h-full')}>
				<SessionProvider session={session}>
					<Providers>
						{children}
					</Providers>
				</SessionProvider>
			</body>
		</html>
	);
}
